language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 10.13
  - 12
  - 14
  - node
install:
  - yarn
script:
  - yarn lint
  - yarn build
  - yarn test
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release@15
  on:
    branch: master
    node_js: '14'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
