language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
install:
  - yarn
script:
  - yarn lint
  - yarn build
  - yarn test
after_success:
  - npm install -g semantic-release@11 travis-deploy-once@4
  - travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
